# Generated by Django 5.2.7 on 2025-11-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to='cards/'),
        ),
    ]
