# Generated by Django 5.2.7 on 2025-11-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_card_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='iamge',
            new_name='image',
        ),
    ]
