# Generated by Django 4.2.26 on 2025-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sub', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.JSONField()),
                ('pidx', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('purchase_order_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Purchase Histories',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
